services:
  sql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - 3306:3306
    networks:
      - wist-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h sql --silent"]
      interval: 10s
      timeout: 5s
      retries: 5
  api:
    depends_on:
      sql:
        condition: service_healthy
    build: .
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://sql:3306/${MYSQL_DATABASE}
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 8080:8080
    restart: always
    networks:
      - wist-network
networks:
  wist-network:
    driver: bridge