#to-do: fix compose, broken connection between api and database
services:
  database:
    image: mysql:8.0
    env_file:
      - ./database.env
    ports:
      - 3306:3306
    networks:
      - wist-app-networks
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - wist-app-networks
    depends_on:
      - database
networks:
    wist-app-networks:
      driver: bridge